# Post a demo record

POST http://localhost:8095/api/v1/health-info
Content-Type: application/json
{
"account_type": "guest",
"email": "demo@example.com",
"exposed": false,
"symptomatic": false,
"name": "John Smith",
"phone": "555 525-2231",
}

# Get a list of all responses

GET http://localhost:8095/health-screening/api/v1/health-info

# Retrieve current user info

GET http://localhost:8095/api/v1/health-info
