# Post a demo record

POST http://localhost:8095/api/v1/health-info
Content-Type: application/json
{
"account_type": "guest",
"confirmation": true,
"congested": false,
"coughing": false,
"diarrhea": false,
"email": "demo@example.com",
"exposed": false,
"feverish": false,
"headache": false,
"loss_of_taste_or_smell": false,
"muscle_ache": false,
"name": "John Smith",
"nauseous": false,
"phone": "555 525-2231",
"tested_positive": false,
"short_of_breath": false,
"sore_throat": false
}

# Get a list of all responses

GET http://localhost:8095/health-screening/api/v1/health-info

# Retrieve current user info

GET http://localhost:8095/api/v1/health-info
