# Post a demo record

POST http://localhost:8080/api/v1/health-info
Content-Type: application/json
{
"accountType": "student",
"phone": "5555555555",
"email": "student@oakland.edu",
"coughing": false,
"feverish": false,
"exposed": false
}

# Get a list of all responses

GET http://localhost:8080/api/v1/health-info
